# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

export HISTTIMEFORMAT="%d-%m-%Y %T "
export PS1='[\u@\h \W]\$ '
export PS2='> '
export PS4='+ '

# User specific environment and startup programs
