forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apache', '3.1.0'
mod 'puppet-php', '5.3.0'

mod 'example42/yum' , "2.1.29"
mod 'jfryman/selinux', "0.4.0"

mod 'saz-sudo'

mod 'camptocamp-systemd'